version: "3"

services:
  etcd1:
    container_name: etcd1
    image: quay.io/coreos/etcd:v3.5.1
    entrypoint: /usr/local/bin/etcd
    command:
      - "--name=etcd1"
      - "--initial-advertise-peer-urls=http://etcd1:2380"
      - "--listen-peer-urls=http://0.0.0.0:2380"
      - "--listen-client-urls=http://0.0.0.0:2379"
      - "--advertise-client-urls=http://etcd1:2379"
      - "--initial-cluster-token=etcd-cluster-secret"
      - "--heartbeat-interval=250"
      - "--election-timeout=1250"
      - "--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      - "--initial-cluster-state=new"
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - /tmp/etcd1:/etcd_data
  etcd2:
    container_name: etcd2
    image: quay.io/coreos/etcd:v3.5.1
    entrypoint: /usr/local/bin/etcd
    command:
      - "--name=etcd2"
      - "--initial-advertise-peer-urls=http://etcd2:2380"
      - "--listen-peer-urls=http://0.0.0.0:2380"
      - "--listen-client-urls=http://0.0.0.0:2379"
      - "--advertise-client-urls=http://etcd2:2379"
      - "--initial-cluster-token=etcd-cluster-secret"
      - "--heartbeat-interval=250"
      - "--election-timeout=1250"
      - "--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      - "--initial-cluster-state=new"
    ports:
      - "22379:2379"
      - "22380:2380"
    volumes:
      - /tmp/etcd2:/etcd_data
  etcd3:
    container_name: etcd3
    image: quay.io/coreos/etcd:v3.5.1
    entrypoint: /usr/local/bin/etcd
    command:
      - "--name=etcd3"
      - "--initial-advertise-peer-urls=http://etcd3:2380"
      - "--listen-peer-urls=http://0.0.0.0:2380"
      - "--listen-client-urls=http://0.0.0.0:2379"
      - "--advertise-client-urls=http://etcd3:2379"
      - "--initial-cluster-token=etcd-cluster-secret"
      - "--heartbeat-interval=250"
      - "--election-timeout=1250"
      - "--initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      - "--initial-cluster-state=new"
    ports:
      - "32379:2379"
      - "32380:2380"
    volumes:
      - /tmp/etcd3:/etcd_data
