package codegens

const (
	clientTmpl = `// Package {{.Pkg}} generated by gbioc. DO NOT EDIT.
package {{.Pkg}}

import (
	"fmt"

	"github.com/anqur/gbio/clients"
	"github.com/anqur/gbio/endpoints"
)

type (
	tx struct{ cl *clients.Client }

{{range .Interfaces}}
	tx{{.Name}} struct{ *clients.Endpoint }
{{end}}
)

var Tx = &tx{cl: clients.Default}

func With(cl *clients.Client) *tx { return &tx{cl: cl} }

func (t *tx) Greeting(opts ...endpoints.Option) *greetingTx {
	ep := &clients.Endpoint{Cl: t.cl}
	ep.Tag = endpoints.DefaultTag

	for _, opt := range opts {
		opt(&ep.Endpoint)
	}

	ep.Name = fmt.Sprintf("hello.Greeting/%s", ep.Tag)
	ep.BaseURI = fmt.Sprintf("/Greeting/%s/SayHi", ep.Tag)
	return &greetingTx{Endpoint: ep}
}

func (t *greetingTx) SayHi(req *SelfIntro) *OkReply {
	httpReq, err := t.Cl.Request(t.Name, t.BaseURI, &SelfIntroEncoder{req})
	if err != nil {
		t.Error = err
		return nil
	}

	httpResp, err := t.Cl.HttpClient().Do(httpReq)
	if err != nil {
		t.Error = err
		return nil
	}

	resp, err := NewDecoder(httpResp.Body, httpResp.Header).OkReply()
	if err != nil {
		t.Error = err
		return nil
	}

	return resp
}
`
)
